#!/usr/bin/bash


# test connectivity
function internet {
    ping google.com -c 1 > /dev/null || echo "#FF0000"
}

function b {

    TYPE=$1
    if [ "$1" != "rx" -a "$1" != "tx" ]; then
        echo "Invalid argument: $1" 1>&2
        echo "Must be 'tx' or 'rx'" 1>&2
        echo "Usage: $0 (rx|tx)" 1>&2
        exit 1
    fi

    FILE=/tmp/i3blocks_bandwidth_$TYPE
    touch $FILE

    PREV=$(cat $FILE)
    CUR=0

    NETDIR=/sys/class/net
    for IFACE in $(ls -1 $NETDIR); do
        # Skip the loopback interface
        if [ "$IFACE" == "wl3s0" ]; then
            continue
        fi
        F=$NETDIR/$IFACE/statistics/${TYPE}_bytes
        N=$(cat $F)
        CUR=$(expr $CUR + $N)
    done

    delta=$(expr $CUR - $PREV)
    echo $(expr $delta / 1000)
    echo $CUR > $FILE



}

function bandwidth {
    rx=$(b rx)
    tx=$(b tx)
    ret="$1"
    if [ "$rx" -ge "10" ]
    then
        ret="$ret "
    else
        ret="$ret  "
    fi

    if [ "$tx" -ge "10" ]
    then
        ret="$ret "
    else
        ret="$ret  "

    fi

    echo "$ret"
    echo "$ret"

}

# decocher pour nm-applet add
# pid=$(pidof nm-applet)
iw=$(iwgetid -r)

if [[ ! -n $pid ]];
then
    {
        if [[ ! -n $iw ]];
        then
            {
                echo "WifiDown"
                echo "WifiDown"
                echo "#FF0000"
            }

        else
            {
                # bandwidth "$iw"
                echo "$iw"
                echo "$iw"
                internet

            }
        fi
    }
fi
exit 0
