#!/bin/bash
clem_id=$(pidof clementine)

# check if clementine active
if [[ -n $clem_id ]]; then
    #qdbus or qdbus-qt4
    TRACK=`qdbus org.mpris.clementine /TrackList org.freedesktop.MediaPlayer.GetCurrentTrack`

    #Check if track runnning
    if [[ $TRACK == -1 ]]; then
        exit 0
    fi

    DISPLAY_TRACK=$(qdbus org.mpris.clementine /Player  org.freedesktop.MediaPlayer.GetMetadata \
                        | sort -r | egrep "^(title:|artist:)" | sed -e "s/^.*: //g" \
                        | sed -e ':a;N;$!ba;s/\n/ - /g' | iconv -f utf-8 -t ascii//TRANSLIT)
    DISPLAY_TRACK_SHORT=$(qdbus org.mpris.clementine /Player  org.freedesktop.MediaPlayer.GetMetadata \
                              | sort -r | egrep "^(title:|artist:)" | sed -e "s/^.*: //g" \
                              | sed -e ':a;N;$!ba;s/\n/ - /g' | head -c 15 \
                              | iconv -f utf-8 -t ascii//TRANSLIT)
    STATUS=$(qdbus --literal org.mpris.clementine /Player org.freedesktop.MediaPlayer.GetStatus | sed -e "s/,//g" | awk  '{print $3}' | head -c 1)

    if [ $STATUS == 1 ] ; then
        TIME=" [Paused]"
    else
        POSITION=$(qdbus org.mpris.clementine /Player org.freedesktop.MediaPlayer.PositionGet)
        TOTAL_TIME=$(qdbus org.mpris.clementine /Player org.freedesktop.MediaPlayer.GetMetadata | sort -r | egrep "mtime" | awk '{print $2}')
        TIME=' ['$(expr $(expr $POSITION \* 100) / $TOTAL_TIME)'%]'
    fi

    echo "${DISPLAY_TRACK}${TIME}"
    echo "${DISPLAY_TRACK_SHORT}${TIME}"
    echo ""

    if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
        qdbus org.mpris.clementine /Player org.freedesktop.MediaPlayer.Pause
    elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
        qdbus org.mpris.clementine /Player org.freedesktop.MediaPlayer.Prev
    elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
        qdbus org.mpris.clementine /Player org.freedesktop.MediaPlayer.Next
    fi

fi
