#!/bin/bash

URGENT_VALUE=90
MEDIUM_VALUE=50
URGENT_VALUE_COLOR="#ff0000"
MEDIUM_VALUE_COLOR="#ffe600"
CPU_USAGE=`{ head -n1 /proc/stat;sleep 0.2;head -n1 /proc/stat; } | awk '/^cpu /{u=$2-u;s=$4-s;i=$5-i;w=$6-w}END{print int(0.5+100*(u+s+w)/(u+s+i+w))}'`

if [[ "${CPU_USAGE}" -gt 0 ]] && [[ "${CPU_USAGE}" -ge "${URGENT_VALUE}" ]]; then
    echo "${CPU_USAGE}%"
    echo "${CPU_USAGE}%"
    echo "${URGENT_VALUE_COLOR}"
elif [[ "${CPU_USAGE}" -gt 0 ]] && [[ "${CPU_USAGE}" -ge "${MEDIUM_VALUE}" ]]; then
    echo "${CPU_USAGE}%"
    echo "${CPU_USAGE}%"
    echo "${MEDIUM_VALUE_COLOR}"
else
    echo "${CPU_USAGE}%"
    echo "${CPU_USAGE}%"
    echo "${NO_VALUE_COLOR}"
fi
