#!/bin/bash
# Source: http://askubuntu.com/a/450136

URGENT_VALUE=90
MEDIUM_VALUE=50
PREV_TOTAL=0
PREV_IDLE=0
URGENT_VALUE_COLOR="#ff0000"
MEDIUM_VALUE_COLOR="#ffe600"
NO_VALUE_COLOR=""

cpuFile="/tmp/.cpu"

if [[ -f "${cpuFile}" ]]; then
  fileCont=$(cat "${cpuFile}")
  PREV_TOTAL=$(echo "${fileCont}" | head -n 1)
  PREV_IDLE=$(echo "${fileCont}" | tail -n 1)
fi

CPU=(`cat /proc/stat | grep '^cpu '`) # Get the total CPU statistics.
unset CPU[0]                          # Discard the "cpu" prefix.
IDLE=${CPU[4]}                        # Get the idle CPU time.

# Calculate the total CPU time.
TOTAL=0

for VALUE in "${CPU[@]:0:4}"; do
  let "TOTAL=$TOTAL+$VALUE"
done

if [[ "${PREV_TOTAL}" != "" ]] && [[ "${PREV_IDLE}" != "" ]]; then
  # Calculate the CPU usage since we last checked.
  let "DIFF_IDLE=$IDLE-$PREV_IDLE"
  let "DIFF_TOTAL=$TOTAL-$PREV_TOTAL"
  let "DIFF_USAGE=(1000*($DIFF_TOTAL-$DIFF_IDLE)/$DIFF_TOTAL+5)/10"
  if [[ "${DIFF_USAGE}" -gt 0 ]] && [[ "${DIFF_USAGE}" -ge "${URGENT_VALUE}" ]]; then
    echo "${DIFF_USAGE}%"
    echo "${DIFF_USAGE}%"
    echo "${URGENT_VALUE_COLOR}"
  elif [[ "${DIFF_USAGE}" -gt 0 ]] && [[ "${DIFF_USAGE}" -ge "${MEDIUM_VALUE}" ]]; then
    echo "${DIFF_USAGE}%"
    echo "${DIFF_USAGE}%"
    echo "${MEDIUM_VALUE_COLOR}"
  else
    echo "${DIFF_USAGE}%"
    echo "${DIFF_USAGE}%"
    echo "${NO_VALUE_COLOR}"
  fi
else
  echo "?"
  echo "?"
  echo ""
fi

# Remember the total and idle CPU times for the next check.
echo "${TOTAL}" > "${cpuFile}"
echo "${IDLE}" >> "${cpuFile}"
