#!/bin/bash

FORMAT='%Y-%m-%d %A %H:%M'
INSTANCE="${BLOCK_INSTANCE}"
#command=date '+%Y-%m-%d %A %H:%M'
COLOR=''
if [[ "${BLOCK_BUTTON}" -eq 1 ]] || [[ "${BLOCK_BUTTON}" -eq 2 ]] || [[ "${BLOCK_BUTTON}" -eq 3 ]]
then
    DATETIME=$(TZ="${INSTANCE}" date "+${FORMAT}" )
    COLOR='#00aa00'
else
    DATETIME=$(date "+${FORMAT}")
    COLOR=''
fi

echo "${DATETIME}"
echo "${DATETIME}"
echo "${COLOR}"
