#!/bin/bash

TYPE="${BLOCK_INSTANCE:-caps}"

lockLine=$(xset -q | grep "Num Lock")

capsLock=$(echo "${lockLine}" | awk -F ' ' '{print $4}')
numLock=$(echo "${lockLine}" | awk -F ' ' '{print $8}')
scrollLock=$(echo "${lockLine}" | awk -F ' ' '{print $12}')

if [[ "${TYPE}" == "caps" ]]; then
  if [[ "${capsLock}" == "on" ]]; then
    echo "on"
    echo "on"
    echo ""
  fi
elif [[ "${TYPE}" == "num" ]]; then
  if [[ "${numLock}" == "off" ]]; then
    echo "off"
    echo "off"
    echo ""
  fi
else
  exit
fi
