#!/bin/bash

INSTANCE="${BLOCK_INSTANCE:-1}"

load=$(cat /proc/loadavg | awk -F ' ' '{print $'"${INSTANCE}"'}')

cpus="$(nproc)"

# full text
echo "$load"

# short text
echo "$load"

load=${load%.*}
# color if load is too high
if [[ "${load}" -ge "${cpus}" ]]; then
    echo "#FF0000"
else
    echo ''
fi
