#!/bin/bash

MEMORY_H=$(awk '/^-/ {print $4}' <(free -h))
MEMORY=$(awk '/^-/ {print $4}' <(free))
MEMORY_TOTAL=$(free | awk 'NR==2{print $2}')
MEMORY_PERC=$(echo "scale=0; (${MEMORY}*100)/${MEMORY_TOTAL}" | bc -l)
URGENT_FREE_VALUE='10'
echo "${MEMORY_H}"
echo "${MEMORY_H}"

if [[ "${MEMORY_PERC}" -lt "${URGENT_FREE_VALUE}" ]]; then
    echo "#FF0000";
    #  exit 33
else
    echo ""
fi
