#!/bin/bash
#country/city
COUNTRY_CITY="${BLOCK_INSTANCE}"

COLOR='#FFFFFF'
#stupid stuff
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
    COLOR='#FF1111'
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
    COLOR='#11FFFF'
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
    COLOR='#11FF11'
elif [[ "${BLOCK_BUTTON}" -eq 4 ]]; then
    COLOR='#1111FF'
elif [[ "${BLOCK_BUTTON}" -eq 5 ]]; then
    COLOR='#111111'
fi

function no_negative() {
    num=$1
    if((num<0));then
        ((num=num+86400))
    fi
    echo $num
}

FILE="/tmp/sunset.log"
NEEDTOCONNECT=true

date_now=$(date +%F)

if [ -f $FILE ]; then
    date_file=$( tail -n 1 $FILE )
    if [ $date_file = $date_now ]; then
        NEEDTOCONNECT=false
        sunrise=$(tail -n 3 $FILE | head -1)
        sunset=$(tail -n 2 $FILE | head -1)
    fi
fi

if [ $NEEDTOCONNECT = true ]; then
    sunset=$( wget -qO- http://www.sunrise-and-sunset.com/en/sun/$COUNTRY_CITY | grep 'Sunset today' -A 2 | awk 'NR==3{print $1}')
    sunrise=$( wget -qO- http://www.sunrise-and-sunset.com/en/sun/$COUNTRY_CITY | grep 'Sunrise today' -A 2 | awk 'NR==3{print $1}')

    echo $sunrise > $FILE
    echo $sunset >> $FILE
    echo $date_now >> $FILE
fi



countdown_sunset_sec=$(no_negative $(($(date -d $sunset +%s) - $(date +%s) + 1)))
countdown_sunrise_sec=$(no_negative $(($(date -d $sunrise +%s) - $(date +%s) + 1)))

if [ $countdown_sunrise_sec -lt $countdown_sunset_sec ];then
    up_or_down=""
    num=$countdown_sunrise_sec
else
    up_or_down=''
    num=$countdown_sunset_sec
fi

min=0
hour=0
if((num>59));then
    ((sec=num%60))
    ((num=num/60))
    if((num>59));then
        ((min=num%60))
        ((num=num/60))
        ((hour=num))
    else
        ((min=num))
    fi
else
    ((sec=num))
fi
if((min<10));then
    min=0$min
fi

countdown_final=$up_or_down' '$hour:$min

if [ $NEEDTOCONNECT = true ]; then
    countdown_final=$countdown_final!
fi

echo $countdown_final
echo $countdown_final
echo $COLOR
