#!/bin/bash

ICON_SUNNY=""
ICON_CLOUDY=""
ICON_RAINY=""
ICON_STORM=""
ICON_SNOW=""
ICON_FOG=""

SYMBOL_CELSIUS="C"

WEATHER_URL="https://weather.gc.ca/city/pages/sk-40_metric_e.html"
FULL_MESSAGE=""
SHORT_MESSAGE=""

WEATHER_INFO=$(wget -qO- "${WEATHER_URL}")
#WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -P '(?<=wxo-metric-hide">).*(?=&deg;)' | head -n 1)
WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -P '(?<=wxo-metric-hide">).*(?=<abbr title="Celsius">)' | head -n 1)
WEATHER_MAIN=$(echo "${WEATHER_INFO}" |  grep -o -P '(?<=<dd class="mrgn-bttm-0">).*(?=</dd>)' | sed -n 3p)
WEATHER_MAIN_SHORT=${WEATHER_MAIN:0:10}

if [ ${#WEATHER_TEMP} -ge 5 ] || [ ${#WEATHER_MAIN} -ge 60 ] ; then
    echo "Weather parse error"
    echo "WPE"
    echo "#FF0000"
    exit
fi

if [[ "${BLOCK_BUTTON}" -eq 1 ]] || [[ "${BLOCK_BUTTON}" -eq 2 ]] || [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
    FULL_MESSAGE=" "${WEATHER_MAIN}" "
    SHORT_MESSAGE=" "${WEATHER_MAIN_SHORT}" "
fi


if [[ "${WEATHER_MAIN}" = *Snow* ]] || [[ "$WEATHER_MAIN" = *Ice* ]]; then
    echo "${ICON_SNOW} ${FULL_MESSAGE}${WEATHER_TEMP}${SYMBOL_CELSIUS}"
    echo "${ICON_SNOW} ${SHORT_MESSAGE}${WEATHER_TEMP}${SYMBOL_CELSIUS}"
    echo '#00FFFF'
elif [[ "${WEATHER_MAIN}" = *Rain* ]] || [[ "${WEATHER_MAIN}" = *Drizzle* ]]; then
    echo "${ICON_RAINY} ${FULL_MESSAGE}${WEATHER_TEMP}${SYMBOL_CELSIUS}"
    echo "${ICON_RAINY} ${SHORT_MESSAGE}${WEATHER_TEMP}${SYMBOL_CELSIUS}"
    echo "#0066FF"
elif [[ "${WEATHER_MAIN}" = *Cloud* ]]; then
    echo "${ICON_CLOUDY} ${FULL_MESSAGE}${WEATHER_TEMP}${SYMBOL_CELSIUS}"
    echo "${ICON_CLOUDY} ${SHORT_MESSAGE}${WEATHER_TEMP}${SYMBOL_CELSIUS}"
    echo ""
elif [[ "${WEATHER_MAIN}" = *Clear* ]] || [[ "${WEATHER_MAIN}" = *Sun* ]]; then
    echo "${ICON_SUNNY} ${FULL_MESSAGE}${WEATHER_TEMP}${SYMBOL_CELSIUS}"
    echo "${ICON_SUNNY} ${SHORT_MESSAGE}${WEATHER_TEMP}${SYMBOL_CELSIUS}"
    echo ""
elif [[ "${WEATHER_MAIN}" = *Fog* ]] || [[ "${WEATHER_MAIN}" = *Mist* ]]; then
    echo "${ICON_FOG} ${FULL_MESSAGE}${WEATHER_TEMP}${SYMBOL_CELSIUS}"
    echo "${ICON_FOG} ${SHORT_MESSAGE}${WEATHER_TEMP}${SYMBOL_CELSIUS}"
    echo ""
elif [[ "${WEATHER_MAIN}" = *Storm* ]] || [[ "${WEATHER_MAIN}" = *Thunderstorm* ]]; then
    echo "${ICON_STORM} ${FULL_MESSAGE}${WEATHER_TEMP}${SYMBOL_CELSIUS}"
    echo "${ICON_STORM} ${SHORT_MESSAGE}${WEATHER_TEMP}${SYMBOL_CELSIUS}"
    echo "#FFFF00"
else
    echo "${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
    echo "${WEATHER_MAIN_SHORT} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
    echo ""
fi
